config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :vehicles
  end

  resources :vehicles

  root to: 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true,
            length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render 'new'
    end
  end

  def new
    @vehicle = Vehicle.new
    @vehicle.category_id = params[:category_id]
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
      redirect_to vehicle_path(@vehicle)
    else
      render 'edit'
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to :back
  end

  def vehicle_params
    params.require(:vehicle).permit(:name, :color, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/categories/_vehicle.html.erb
  <tr>
    <td><%= vehicle.name %></td>
    <td><%= color_field_tag 'color', vehicle.color, disabled: true %></td>
    <td><%= link_to "Show", category_vehicle_path(vehicle.category, vehicle) %></td>
    <td><%= link_to "Edit", edit_category_vehicle_path(vehicle.category, vehicle) %></td>
    <td>
      <%= link_to "Delete",
        category_vehicle_path(vehicle.category, vehicle),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </td>
    </td>
  </tr>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<ul>
  <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Color </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'categories/vehicle', collection: @category.vehicles %>
  <tbody>
</table>
<p>
<%= link_to "+ New " + @category.name.singularize, new_category_vehicle_url(@category) %>
<p><%= link_to "<< Back to Categories List", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestVehicles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vehicles/_form.html.erb
<% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@vehicle.errors.count, "error") %> prohibited
        this vehicle from being saved:
      </h2>
      <ul>
        <% @vehicle.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for [@category, @vehicle], :html => {:id => 'edit_vehicle', :name => 'edit_vehicle' } do |f| %>
    <%= f.hidden_field :category_id %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name%>
    </p>
    <p>
      <%= f.label :color %><br/>
      <%= f.color_field :color %>
    </p>
    <p>
      <%= f.button 'Submit' %>
    </p>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
    $("#edit_vehicle").validate({
      rules: {"vehicle[name]": {required: true, minlength: 8}}
    });
  });

  $( "button" ).click(function() {
    if ($("#edit_vehicle").valid()) {alert("Validation Ok")}
    else {alert("Validation failed !!!")};
  });

</script>

app/views/vehicles/edit.html.erb
<h3>Edit  <%= @vehicle.category.name.singularize %> </h3>
<%= render partial: 'form' %>

app/views/vehicles/new.html.erb
<h3>New  <%= @vehicle.category.name.singularize %> </h3>
<%= render partial: 'form' %>

app/views/vehicles/show.html.erb
<h3><%= @vehicle.category.name.singularize%></h3>
<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>
<p>
  <strong>Color:</strong>
  <%= color_field_tag 'color', @vehicle.color, disabled: true %>
</p>
<%= link_to "<< Back to " + @vehicle.category.name +  " List", category_path(@vehicle.category) %>